#!/usr/bin/env python3
"""
build_html.py — Quiz Atelier's HTML page, expressed as Python.

This file is the SOURCE OF TRUTH for the app's static markup. Each UI
section is a function returning an HTML string; build() composes them
and writes ../index.html. The generated file is byte-identical to the
hand-written original, so the server/APK/SW need no changes.

Run from this directory:  python build_html.py
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "index.html"


# ─── tiny helpers ────────────────────────────────────────────────────
def tag(name: str, attrs: str = "", *children: str, self_close: bool = False) -> str:
    """An element with a raw attribute string and pre-rendered children."""
    open_ = f"<{name}{' ' + attrs if attrs else ''}>"
    return f"{open_}{''.join(children)}</{name}>" if not self_close else f"<{name}{' ' + attrs if attrs else ''} />"


def icon(use_id: str, cls: str = "ico") -> str:
    return f'<svg class="{cls}" aria-hidden="true"><use href="#{use_id}"></use></svg>'


# ─── 0. doctype + head ───────────────────────────────────────────────
def head_section() -> str:
    return f'''<!doctype html>
<!--
  Quiz Atelier — quiz management system, two-personalised workspaces.
  Single self-contained artifact built per the repo's web-prototype +
  frontend-design skills: paper/ink editorial design system, one coral
  accent, serif display type, mono numerics, real state coverage.

  Roles — the app opens with a role gate and adapts everything to who
  is signed in:
    · Teacher — Quiz Ledger grouped by subject (recently conducted,
      average marks, % of the class that attended), builder, full
      results ledger, roster, AI generator.
    · Student — My Subjects, quizzes available to take, personal
      score history vs class average, private AI practice. Builder
      is hidden.

  Structure:
    1. App chrome  (brand rail + main column)
    2. Login gate  (choose Student/Teacher, then email sign-in)
    3. Dashboard   (teacher: subject ledger · student: my subjects)
    4. Builder     (New Quiz | editor · Questions | Class Roster)
    5. Results     (teacher: class ledger · student: my scores)
    6. Player      (take-quiz modal: intro → questions → results)
    7. Dialogs     (confirm + import + cookie consent)

  NOTE: this file is GENERATED by python/build_html.py — edit the
  Python sections, then run `python build_html.py` to regenerate.
-->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="default" />
  <link rel="manifest" href="/manifest.webmanifest" />
  <meta name="theme-color" content="#efe7d2" />
  <title>Quiz Atelier — Quiz Management</title>
  <link rel="stylesheet" href="styles.css" />
  <link rel="icon" href="favicon.ico" sizes="48x48" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
</head>
<body>'''


# ─── 1. skip link ────────────────────────────────────────────────────
def skip_link() -> str:
    return '  <a class="skip-link" href="#main">Skip to main content</a>'


# ─── 2. login gate ───────────────────────────────────────────────────
def login_gate() -> str:
    gate_mark = tag(
        "div", 'class="gate-mark gate-mark--logo" aria-hidden="true"',
        '<svg viewBox="0 0 48 48" role="img" aria-label="Quiz Atelier logo">'
        '<circle cx="24" cy="24" r="21" fill="var(--surface)" stroke="currentColor" stroke-width="2.4"/>'
        '<text x="11.4" y="32" font-family="Georgia, serif" font-size="31" font-weight="700" fill="currentColor">Q</text>'
        '<path d="M27.5 20.5 L36.5 29.5" stroke="var(--coral)" stroke-width="3.6" stroke-linecap="round"/>'
        '<path d="M24 18.5 C29 13.5 35 14.5 37.5 19 C34 23.5 28 23 24 19.5 Z" fill="var(--coral)" stroke="currentColor" stroke-width="1.1"/>'
        '<path d="M37.5 28 C34 22 28.5 19.5 24 19.5 C27.5 23 31 26.5 33.5 30.5 Z" fill="var(--olive)" stroke="currentColor" stroke-width="1.1"/>'
        '<path d="M31 9.5 L32.3 12.8 L35.6 14.1 L32.3 15.4 L31 18.7 L29.7 15.4 L26.4 14.1 L29.7 12.8 Z" fill="var(--mustard)"/>'
        '</svg>',
    )
    student_ico = (
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" '
        'stroke-linejoin="round"><path d="M22 10L12 5 2 10l10 5 10-5z" />'
        '<path d="M6 12v5c0 1.7 2.7 3 6 3s6-1.3 6-3v-5" /></svg>'
    )
    teacher_ico = (
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" '
        'stroke-linejoin="round"><path d="M12 3L2 8l10 5 10-5-10-5z" />'
        '<path d="M6 10.5V16c0 1.5 2.7 2.5 6 2.5s6-1 6-2.5v-5.5" /><path d="M22 8v6" /></svg>'
    )
    return f'''  <!-- ══════════════════ Login gate (choose role → email sign in) ══════════════════ -->
  <div class="role-gate" id="login-gate" hidden>
    <div class="gate-card" role="dialog" aria-modal="true" aria-labelledby="login-title">
      {gate_mark}
      <p class="eyebrow">Quiz Atelier</p>
      <h1 class="gate-title" id="login-title">Welcome to Quiz Atelier</h1>
      <p class="gate-note" id="login-note">First, tell us who's here.</p>

      <div class="gate-choices" id="gate-choices">
        <button class="gate-opt" type="button" id="gate-student">
          <span class="gate-ico" aria-hidden="true">
            {student_ico}
          </span>
          <span class="gate-name">Student</span>
          <span class="gate-desc">Take quizzes, track your scores and subjects.</span>
        </button>
        <button class="gate-opt" type="button" id="gate-teacher">
          <span class="gate-ico" aria-hidden="true">
            {teacher_ico}
          </span>
          <span class="gate-name">Teacher</span>
          <span class="gate-desc">Build quizzes, run them and read the room's ledger.</span>
        </button>
      </div>

      <form class="gate-form" id="login-form" novalidate hidden>
        <div class="field">
          <label for="login-user">Email</label>
          <input class="input" id="login-user" name="login-user" type="email" autocomplete="email"
                 spellcheck="false" placeholder="you@school.edu" />
        </div>
        <div class="field" id="login-name-field" hidden>
          <label for="login-name">Full name <span class="opt">(new accounts)</span></label>
          <input class="input" id="login-name" name="login-name" type="text" autocomplete="name"
                 spellcheck="false" placeholder="Your full name" />
        </div>
        <div class="field">
          <label for="login-pass">Password</label>
          <input class="input" id="login-pass" name="login-pass" type="password"
                 autocomplete="current-password" placeholder="••••••••" />
          <p class="field-error" id="login-pass-error" hidden>At least 6 characters.</p>
        </div>
        <p class="field-error" id="login-error" role="alert" hidden></p>
        <button class="btn btn--primary" type="submit" id="btn-login">Sign In</button>
        <button class="btn btn--ghost gate__back" type="button" id="btn-gate-back">← Back</button>
      </form>

      <div class="demo-creds" aria-label="Demo credentials">
        <p class="demo-creds__title">Demo credentials — click Use to fill</p>
        <div class="demo-creds__row">
          <span class="demo-creds__who">Teacher</span>
          <span class="demo-creds__key num">teacher@quiz.dev / teacher123</span>
          <button class="btn btn--outline btn--sm" type="button" data-fill="teacher">Use</button>
        </div>
        <div class="demo-creds__row">
          <span class="demo-creds__who">Student</span>
          <span class="demo-creds__key num">student@quiz.dev / student123</span>
          <button class="btn btn--outline btn--sm" type="button" data-fill="student">Use</button>
        </div>
      </div>
    </div>
  </div>'''


# ─── 3. cookie consent ───────────────────────────────────────────────
def consent_banner() -> str:
    return f'''  <!-- ══════════════════ Cookie consent (bottom-left) ══════════════════ -->
  <div class="consent" id="consent-banner" role="dialog" aria-modal="false"
       aria-labelledby="consent-title" hidden>
    <button class="consent__close" type="button" id="btn-consent-close"
            aria-label="Close — treated as rejecting cookies" title="Dismiss (asks again next visit)">
      {icon("i-x")}
    </button>
    <h2 class="consent__title" id="consent-title">Cookies Consent</h2>
    <p class="consent__text">Quiz Atelier is open-source and collects no personal data — no analytics, no tracking, no ads.</p>
    <p class="consent__text">The one thing cookies do here is remember your <strong>login</strong> so you stay signed in on your next visit. Accept to keep your session, or reject and you'll simply sign in each time.</p>
    <div class="consent__actions">
      <button class="btn btn--outline" type="button" id="btn-consent-reject">Reject Cookies</button>
      <button class="btn btn--primary" type="button" id="btn-consent-accept">Accept Cookies</button>
    </div>
  </div>'''


# ─── 4. brand rail (desktop sidebar) ─────────────────────────────────
def brand_rail() -> str:
    rail_mark = (
        '<svg class="rail__mark rail__mark--logo" viewBox="0 0 48 48" aria-hidden="true">'
        '<circle cx="24" cy="24" r="21" fill="var(--surface)" stroke="currentColor" stroke-width="2.4"/>'
        '<text x="11.4" y="32" font-family="Georgia, serif" font-size="31" font-weight="700" fill="currentColor">Q</text>'
        '<path d="M27.5 20.5 L36.5 29.5" stroke="var(--coral)" stroke-width="3.6" stroke-linecap="round"/>'
        '<path d="M24 18.5 C29 13.5 35 14.5 37.5 19 C34 23.5 28 23 24 19.5 Z" fill="var(--coral)" stroke="currentColor" stroke-width="1.1"/>'
        '<path d="M37.5 28 C34 22 28.5 19.5 24 19.5 C27.5 23 31 26.5 33.5 30.5 Z" fill="var(--olive)" stroke="currentColor" stroke-width="1.1"/>'
        '<path d="M31 9.5 L32.3 12.8 L35.6 14.1 L32.3 15.4 L31 18.7 L29.7 15.4 L26.4 14.1 L29.7 12.8 Z" fill="var(--mustard)"/>'
        '</svg>'
    )
    rail_nav = [
        ("dashboard", "i-gauge", "Dashboard", 'class="rail__link is-active"', 'aria-current="page"'),
        ("leaderboard", "i-bars", "Leaderboard", 'class="rail__link"', ""),
        ("builder", "i-pen", "Quiz Builder", 'class="rail__link"', ""),
        ("results", "i-ledger", None, 'class="rail__link"', ""),   # label wrapped in a span
        ("generate", "i-spark", None, 'class="rail__link"', ""),
    ]
    nav_lines = []
    for nav, ico, label, cls, extra in rail_nav:
        if nav == "results":
            inner = f'{icon(ico)}<span id="rail-results-label">Results</span>'
        elif nav == "generate":
            inner = f'{icon(ico)}<span id="rail-gen-label">AI Generator</span>'
        else:
            inner = f'{icon(ico)}{label}'
        attrs = f'{cls} type="button" data-nav="{nav}"'
        if extra:
            attrs += f" {extra}"
        nav_lines.append(
            f"        <button {attrs}>\n"
            f"          {inner}\n        </button>"
        )
    return f'''  <div class="app" id="app">

    <!-- ══════════════════ Brand rail ══════════════════ -->
    <aside class="rail" data-od-id="rail">
      <a class="rail__brand" href="#" data-nav="dashboard" aria-label="Quiz Atelier — go to dashboard">
        {rail_mark}
        <span>
          <span class="rail__word">Quiz&nbsp;Atelier</span>
          <span class="role-badge" id="role-badge">—</span>
        </span>
      </a>

      <p class="rail__eyebrow" id="rail-nav-eyebrow">Workspace</p>
      <nav class="rail__nav" aria-label="Primary">
{chr(10).join(nav_lines)}
      </nav>

      <div id="rail-teacher-only">
        <p class="rail__eyebrow">Library</p>
        <div class="rail-lib">
          <button class="rail__link" type="button" data-nav="drafts">
            {icon("i-file")}Draft
            <span class="rail-draft-count" id="rail-drafts-count" hidden>0</span>
          </button>
        </div>

        <div class="rail-lib">
          <button class="rail__link" type="button" data-nav="favs">
            {icon("i-star")}Favourites
            <span class="rail-draft-count" id="rail-favs-count" hidden>0</span>
          </button>
        </div>

        <div class="rail-lib">
          <button class="rail__link" type="button" data-nav="bookmarks">
            {icon("i-bookmark")}Templates
            <span class="rail-draft-count" id="rail-bookmarks-count" hidden>0</span>
          </button>
        </div>

        <p class="rail__eyebrow">Data</p>
        <div class="rail__data">
          <button class="btn btn--ghost btn--sm" type="button" id="btn-export">
            {icon("i-download")}Export JSON
          </button>
          <button class="btn btn--ghost btn--sm" type="button" id="btn-import">
            {icon("i-upload")}Import JSON
          </button>
          <button class="btn btn--ghost btn--sm" type="button" id="btn-reset">
            {icon("i-trash")}Delete Account
          </button>
        </div>
      </div>

      <div id="rail-student-only" hidden>
        <p class="rail__eyebrow">Library</p>
        <div class="rail-lib">
          <button class="rail__link" type="button" data-nav="favs">
            {icon("i-star")}Favourites
            <span class="rail-draft-count" id="rail-student-favs-count" hidden>0</span>
          </button>
        </div>

        <p class="rail__eyebrow">Next Up</p>
        <div id="student-nextup"></div>
      </div>

    </aside>'''


# ─── 5. phone bottom tab bar ─────────────────────────────────────────
def phone_tabbar() -> str:
    tabs = [
        ("dashboard", "i-gauge", "Home", ""),
        ("leaderboard", "i-bars", "Ranks", ""),
        ("builder", "i-pen", "Build", ' data-tab-teacher="1"'),
        ("results", "i-ledger", None, ""),
        ("generate", "i-spark", "AI", ""),
    ]
    lines = []
    for nav, ico, label, extra in tabs:
        if nav == "results":
            inner = f'{icon(ico)}<span id="tab-results-label">Scores</span>'
        else:
            inner = f'{icon(ico)}<span>{label}</span>'
        active = ' class="tabbar__btn is-active"' if nav == "dashboard" else ' class="tabbar__btn"'
        lines.append(
            f'      <button{active} type="button" data-nav="{nav}"{" " + extra.strip() if extra else " "}>\n'
            f"        {inner}\n      </button>"
        )
    return f'''    <!-- ══════════════════ Phone bottom tab bar (≤640px) ═══════════ -->
    <nav class="tabbar" aria-label="Primary — phone">
{chr(10).join(lines)}
    </nav>'''


# ─── 6. topbar (title + theme/bell/account actions) ──────────────────
def topbar() -> str:
    return f'''    <!-- ══════════════════ Main column ══════════════════ -->
    <div class="main-col">
      <header class="topbar" data-od-id="topbar">
        <div class="topbar__titles">
          <p class="eyebrow" id="view-eyebrow">Overview</p>
          <h1 class="topbar__title" id="view-title">Dashboard</h1>
        </div>
        <div class="topbar__actions">
          <div class="topbar-row2">
            <button class="iconbtn" type="button" id="topbar-theme" aria-label="Toggle dark mode" title="Toggle dark mode">
              <svg class="ico theme-ico--sun" aria-hidden="true"><use href="#i-sun"></use></svg>
              <svg class="ico theme-ico--moon" aria-hidden="true"><use href="#i-moon"></use></svg>
            </button>
            <div class="bell-wrap" id="bell-wrap">
              <button class="iconbtn" type="button" id="btn-activity-bell" aria-label="Activity" title="Activity" aria-haspopup="true" aria-expanded="false">
                {icon("i-bell")}
                <span class="bell-dot" id="bell-dot" hidden aria-hidden="true"></span>
              </button>
            </div>
          </div>
          <div class="account-stack">
            <button class="btn btn--primary" type="button" id="btn-open-last" hidden>
              {icon("i-play")}Open Latest
            </button>
            <div class="new-wrap" id="new-menu-wrap">
              <button class="btn btn--outline" type="button" id="btn-new-menu"
                      aria-haspopup="menu" aria-expanded="false" aria-controls="new-menu">
                {icon("i-plus")}New
                <svg class="ico" aria-hidden="true" style="width:12px;height:12px"><use href="#i-chevron"></use></svg>
              </button>
              <div class="account__menu new-menu" id="new-menu" role="menu" aria-label="Create new" hidden>
                <button class="account__item" type="button" role="menuitem" id="menu-new-quiz">
                  {icon("i-pen")}Quiz
                </button>
                <button class="account__item" type="button" role="menuitem" id="menu-new-subject">
                  {icon("i-book")}Subject
                </button>
                <button class="account__item" type="button" role="menuitem" id="menu-new-student">
                  {icon("i-cap")}Student
                </button>
              </div>
            </div>
            <div class="account">
            <button class="btn btn--outline" type="button" id="account-btn" aria-haspopup="menu" aria-expanded="false">
              <span class="avatar avatar--sm" id="account-avatar" aria-hidden="true">?</span>
              <span id="account-name">Account</span>
              <svg class="ico" aria-hidden="true" style="width:12px;height:12px"><use href="#i-chevron"></use></svg>
            </button>
            <div class="account__menu" id="account-menu" role="menu" aria-label="Account" hidden>
              <div class="account__id">
                <p class="account__name" id="account-menu-name">—</p>
                <p class="account__role" id="account-menu-role">—</p>
              </div>
              <button class="account__item" type="button" role="menuitem" id="menu-theme" hidden data-apk-only="1">
                {icon("i-sun")}<span id="menu-theme-label">Theme: Light</span>
              </button>
              <button class="account__item" type="button" role="menuitem" id="menu-plans">
                {icon("i-dollar")}Plans
              </button>
              <!-- data I/O mirrors the desktop rail's Data block — the rail is
                   hidden at phone widths, so the APK needs these here -->
              <button class="account__item" type="button" role="menuitem" id="menu-export" data-teacher-only="1" hidden data-apk-only="1">
                {icon("i-download")}Export JSON
              </button>
              <button class="account__item" type="button" role="menuitem" id="menu-import" data-teacher-only="1" hidden data-apk-only="1">
                {icon("i-upload")}Import JSON
              </button>
              <button class="account__item account__item--danger" type="button" role="menuitem" id="menu-reset" data-teacher-only="1" hidden data-apk-only="1">
                {icon("i-trash")}Delete Account
              </button>
              <button class="account__item" type="button" role="menuitem" id="menu-signout">
                {icon("i-logout")}Sign Out
              </button>
            </div>
          </div>
          </div>
        </div>
        </header>

      <!-- activity popup — anchored under the bell, overlays content -->
      <div class="bell-pop" id="bell-pop" hidden aria-label="Recent activity">
        <div class="bell-pop__head">
          <span class="bell-pop__title">Activity</span>
        </div>
        <ol class="activity bell-pop__list" id="activity-list"></ol>
        <p class="empty empty--tight" id="activity-empty" hidden><span class="empty__note">Nothing logged yet.</span></p>
        <p class="expiry-note">Entries expire within 24 hours.</p>
      </div>

      <main class="main" id="main" tabindex="-1">'''

# ─── 7. leaderboard view ─────────────────────────────────────────────
def view_leaderboard() -> str:
    return '''        <!-- ─────────── Subject Leaderboard ─────────── -->
        <section class="view" id="view-leaderboard" hidden aria-labelledby="lb-title">
          <section class="panel" data-od-id="leaderboard" aria-labelledby="lb-title">
            <div class="panel__head">
              <h2 class="panel__title" id="lb-title">Subject Leaderboard</h2>
            </div>
            <p class="panel-sub" id="lb-sub">Pick a subject to see how everyone stands.</p>
            <div class="lb-subjects" id="lb-subjects" role="tablist" aria-label="Subject"></div>
            <div class="tablewrap">
              <table class="table">
                <caption class="visually-hidden">Ranked students for the selected subject</caption>
                <thead>
                  <tr>
                    <th scope="col" class="num-col">Rank</th>
                    <th scope="col">Student</th>
                    <th scope="col" class="num-col">Quizzes</th>
                    <th scope="col" class="num-col">Avg&nbsp;%</th>
                    <th scope="col" class="num-col">Best</th>
                  </tr>
                </thead>
                <tbody id="lb-tbody"></tbody>
              </table>
              <div class="lb-empty" id="lb-empty" hidden>
                <p class="empty__title">No scores in this subject yet</p>
                <p class="empty__note">Once quizzes are attempted here, the ranking appears.</p>
              </div>
            </div>
          </section>
        </section>'''


# ─── 8. dashboard view (stats + role-specific panels) ────────────────
def _stat_card(idx: str) -> str:
    return f'''            <article class="stat" id="stat-{idx}">
              <p class="stat__label" id="stat-{idx}-label">—</p>
              <p class="stat__num num" id="stat-{idx}-num">0</p>
              <p class="stat__delta" id="stat-{idx}-note">—</p>
            </article>'''


def _rstat_card(idx: str, accent: bool = False) -> str:
    cls = "stat stat--accent" if accent else "stat"
    return f'''            <article class="{cls}" id="rstat-{idx}">
              <p class="stat__label" id="rstat-{idx}-label">—</p>
              <p class="stat__num num" id="rstat-{idx}-num">0</p>
              <p class="stat__delta" id="rstat-{idx}-note">—</p>
            </article>'''


def view_dashboard() -> str:
    stats = "\n\n".join(_stat_card(i) for i in ("1", "2", "3", "4"))
    return f'''        <!-- ─────────── Dashboard ─────────── -->
        <section class="view" id="view-dashboard" data-od-id="view-dashboard" aria-labelledby="view-title">

          <div class="statgrid" data-od-id="stats">
{stats}
          </div>

          <!-- Teacher: subject ledger -->
          <div class="cols" id="teacher-cols">
            <section class="panel" data-od-id="quiz-ledger" aria-labelledby="ledger-title">
              <div class="panel__head">
                <h2 class="panel__title" id="ledger-title">Quiz Ledger</h2>
              </div>
              <p class="panel-sub" id="ledger-sub">Subjects recently conducted, with average marks and attendance. Click a subject to expand its quizzes.</p>

              <div class="tablewrap">
                <table class="table">
                  <caption class="visually-hidden">Subjects with quizzes conducted, average marks, attendance and recent activity</caption>
                  <thead>
                    <tr>
                      <th scope="col">Subject</th>
                      <th scope="col" class="num-col">Quizzes</th>
                      <th scope="col" class="num-col">Conducted</th>
                      <th scope="col" class="num-col">Avg&nbsp;Marks</th>
                      <th scope="col">Attendance</th>
                      <th scope="col" class="num-col">Recent Activity</th>
                    </tr>
                  </thead>
                  <tbody id="quiz-tbody"></tbody>
                </table>
                <div class="empty" id="quiz-empty" hidden>
                  <p class="empty__title">No subjects on file</p>
                  <p class="empty__note">Draft a quiz in the builder — it will appear here.</p>
                  <button class="btn btn--outline" type="button" data-nav="builder">Open Quiz Builder</button>
                </div>
              </div>
            </section>
          </div>

          <!-- Teacher: weekly class digest + student snapshots -->
          <div id="teacher-perks" hidden>
            <section class="panel perk-panel" data-od-id="class-digest" aria-labelledby="digest-week-title">
              <div class="panel__head">
                <h2 class="panel__title" id="digest-week-title">Weekly Class Digest</h2>
                <span class="pill" id="digest-week-pill">This week</span>
              </div>
              <p class="panel-sub">An auto-summary of the last 7 days — refreshed every time you open the dashboard.</p>
              <div class="digest-week-grid" id="digest-week-grid"></div>
              <div class="digest-week-lows" id="digest-week-lows"></div>
            </section>

            <section class="panel perk-panel" data-od-id="student-snapshots" aria-labelledby="snap-title">
              <div class="panel__head">
                <h2 class="panel__title" id="snap-title">Student Snapshots</h2>
                <span class="pill" id="snap-count">0</span>
              </div>
              <p class="panel-sub">Everyone at a glance. Click “Full cards” for detailed per-student view.</p>
              <div class="snap-actions">
                <div class="lib-tools">
                  <label class="lib-search">
                    {icon("i-search")}
                    <input type="search" id="snap-search" placeholder="Search students…" aria-label="Search students by name" />
                  </label>
                  <div class="lib-filter-wrap">
                    <button class="iconbtn iconbtn--sm" type="button" id="snap-filter-btn" aria-haspopup="dialog"
                            aria-expanded="false" aria-controls="snap-filter" title="Filter students">
                      {icon("i-funnel")}
                    </button>
                    <div class="lib-filter snap-filter" id="snap-filter" hidden>
                      <div class="snap-filter-grid">
                        <label>Taken ≥<input class="input" id="snap-flt-taken-min" type="number" min="0" inputmode="numeric" placeholder="e.g. 5" /></label>
                        <label>Taken ≤<input class="input" id="snap-flt-taken-max" type="number" min="0" inputmode="numeric" placeholder="e.g. 20" /></label>
                        <label>Average ≥<input class="input" id="snap-flt-avg-min" type="number" min="0" max="100" inputmode="numeric" placeholder="e.g. 60" /></label>
                        <label>Average ≤<input class="input" id="snap-flt-avg-max" type="number" min="0" max="100" inputmode="numeric" placeholder="e.g. 90" /></label>
                      </div>
                      <div class="snap-filter-checks">
                        <label class="snap-check"><input type="checkbox" id="snap-flt-attended" /> Attended</label>
                        <label class="snap-check"><input type="checkbox" id="snap-flt-unattended" /> Unattended</label>
                      </div>
                      <button class="snap-sort" type="button" id="snap-sort-btn" title="Cycle sort order">
                        <span class="snap-sort__label">Sort:</span>
                        <span class="snap-sort__value" id="snap-sort-value">Name (A-Z)</span>
                      </button>
                      <div class="res-filter-actions">
                        <button class="btn btn--ghost btn--sm" type="button" id="snap-flt-clear">Clear</button>
                        <button class="btn btn--primary btn--sm" type="button" id="snap-flt-apply">Apply</button>
                      </div>
                    </div>
                  </div>
                  <button class="btn btn--outline btn--sm" type="button" id="btn-snap-mode" aria-pressed="false">Full cards</button>
                </div>
              </div>
              <div class="snap-strip" id="snap-strip"></div>
              <div class="snap-cards" id="snap-cards" hidden></div>
            </section>
          </div>

          <!-- Student: streaks, badges, reminders & weekly digest -->
          <div id="student-perks" hidden>
            <section class="panel perk-panel" data-od-id="streak-badges" aria-labelledby="streak-title">
              <div class="panel__head">
                <h2 class="panel__title" id="streak-title">Your Streak</h2>
                <span class="pill" id="streak-pill">0 days</span>
              </div>
              <p class="panel-sub">Practice daily to grow your streak and collect badges.</p>
              <div id="student-streak"></div>
            </section>

            <section class="panel perk-panel" data-od-id="study-habits" aria-labelledby="habits-title">
              <div class="panel__head">
                <h2 class="panel__title" id="habits-title">Study Habits</h2>
              </div>
              <p class="panel-sub">Small nudges to keep you on track — all private to you.</p>

              <div class="habit-row">
                <div class="habit-text">
                  <p class="habit-name">Daily practice reminder</p>
                  <p class="habit-desc" id="reminder-desc">We'll nudge you at your chosen time.</p>
                </div>
                <input class="input input--time" type="time" id="reminder-time" value="18:00" aria-label="Reminder time" />
                <button class="toggle" type="button" id="reminder-toggle" role="switch" aria-checked="false">
                  <span class="toggle__knob"></span>
                </button>
              </div>

              <div class="habit-row">
                <div class="habit-text">
                  <p class="habit-name">Weekly self-digest</p>
                  <p class="habit-desc" id="digest-desc">A summary of your week, emailed every Sunday.</p>
                </div>
                <button class="toggle" type="button" id="digest-toggle" role="switch" aria-checked="false">
                  <span class="toggle__knob"></span>
                </button>
              </div>

              <div class="digest-card" id="digest-card" hidden>
                <p class="digest-title">This week at a glance</p>
                <div class="digest-grid" id="digest-grid"></div>
                <p class="digest-note">Digests are sent from the app's email — check spam if it doesn't arrive.</p>
              </div>
            </section>

            <!-- Spaced repetition: daily warm-up + the Graveyard + comeback scheduling -->
            <section class="panel perk-panel" data-od-id="spaced-repetition" aria-labelledby="warmup-title">
              <div class="panel__head">
                <h2 class="panel__title" id="warmup-title">Today's Warm-up</h2>
                <span class="pill" id="warmup-pill">—</span>
              </div>
              <p class="panel-sub" id="warmup-sub">Five questions from your weakest topics — ready before you've finished your coffee.</p>
              <div id="warmup-host"></div>
            </section>

            <section class="panel perk-panel" data-od-id="graveyard" aria-labelledby="graveyard-title">
              <div class="panel__head">
                <h2 class="panel__title" id="graveyard-title">The Graveyard</h2>
                <span class="pill" id="graveyard-pill">0 resting</span>
              </div>
              <p class="panel-sub">Every question you've ever missed, buried here until you set it free.</p>
              <div id="graveyard-host"></div>
            </section>
          </div>

          <!-- Student: subject ledger — My Subjects + Quizzes Available merged -->
          <div class="cols" id="student-cols">
            <section class="panel" data-od-id="my-subjects" aria-labelledby="subjects-title">
              <div class="panel__head">
                <h2 class="panel__title" id="subjects-title">My Subjects</h2>
                <span class="pill" id="subjects-count">0</span>
              </div>
              <p class="panel-sub" id="subjects-sub">Subjects you've attended, with your standing in each. Click a subject to see its quizzes.</p>

              <div class="tablewrap">
                <table class="table">
                  <caption class="visually-hidden">Subjects attended with quiz counts, last attended date and personal average; expand a subject to see its quizzes</caption>
                  <thead>
                    <tr>
                      <th scope="col">Subject</th>
                      <th scope="col" class="num-col">Taken</th>
                      <th scope="col" class="num-col">Last&nbsp;Attended</th>
                      <th scope="col" class="num-col">Your&nbsp;Avg</th>
                      <th scope="col" class="num-col">Open</th>
                    </tr>
                  </thead>
                  <tbody id="subjects-tbody"></tbody>
                </table>
                <div class="empty" id="subjects-empty" hidden>
                  <p class="empty__title">No subjects yet</p>
                  <p class="empty__note">Once your teacher publishes a quiz, its subject appears here.</p>
                </div>
              </div>
            </section>
          </div>
        </section>'''


# ─── 9. builder view (teacher only) ──────────────────────────────────
def _switch(id_: str, label_id: str, label_html: str, note: str | None = None,
            field: str | None = None) -> str:
    out = f'''                <div class="switchrow">
                  <span class="switch-label" id="{label_id}">{label_html}</span>
                  <button class="switch" type="button" role="switch" id="{id_}"
                          aria-checked="false" aria-labelledby="{label_id}">
                    <span class="switch__thumb"></span>
                  </button>
                </div>'''
    if field:
        out += f"\n{field}"
    if note:
        out += f'\n{note}'
    return out


_TIME_LIMIT_FIELD = '''                <div class="field" id="quiz-time-limit-field" hidden>
                  <label for="quiz-time-limit">Time limit <span class="opt">(minutes)</span></label>
                  <select class="input input--select" id="quiz-time-limit" name="quiz-time-limit">
                    <option value="60">1 minute</option>
                    <option value="120">2 minutes</option>
                    <option value="180">3 minutes</option>
                    <option value="300" selected>5 minutes</option>
                    <option value="600">10 minutes</option>
                    <option value="900">15 minutes</option>
                    <option value="1200">20 minutes</option>
                    <option value="1800">30 minutes</option>
                    <option value="3600">60 minutes</option>
                  </select>
                </div>'''

_SCHEDULE_FIELD = '''                <div class="field" id="quiz-schedule-field" hidden>
                  <label for="quiz-schedule-at">Go live at</label>
                  <input class="input" id="quiz-schedule-at" name="quiz-schedule-at" type="datetime-local" />
                  <p class="field-error" id="quiz-schedule-error" hidden>Pick a future date &amp; time to schedule the quiz.</p>
                </div>'''

_HINTS_NOTE = '''                <p class="hints-note" id="hints-note">Students get a 50/50 lifeline — two wrong options disappear, once per question.</p>'''

_SHUFFLE_NOTE = '''                <p class="hints-note" id="shuffle-note" hidden>Questions are shown in a random order to each student — helpful for shared devices and test integrity.</p>'''


def view_builder() -> str:
    publish = _switch("quiz-publish", "publish-label", "Publish immediately")
    schedule = _switch("quiz-schedule", "schedule-label", "Schedule", field=_SCHEDULE_FIELD)
    timed = _switch("quiz-timed", "timed-label", "Timed quiz", field=_TIME_LIMIT_FIELD)
    hints = _switch("quiz-hints", "hints-label", "Hint system", note=_HINTS_NOTE)
    shuffle = _switch("quiz-shuffle", "shuffle-label", "Shuffle questions", note=_SHUFFLE_NOTE)
    return f'''        <!-- ─────────── Builder (teacher only) ─────────── -->
        <section class="view" id="view-builder" data-od-id="view-builder" aria-labelledby="builder-heading" hidden>
          <h2 class="visually-hidden" id="builder-heading">Quiz Builder</h2>

          <div class="builder-grid" data-od-id="builder-grid">

            <div class="bstack">
              <form class="panel" id="meta-form" data-od-id="quiz-meta" novalidate>
                <div class="panel__head">
                  <h3 class="panel__title" id="meta-form-title">New Quiz</h3>
                </div>
                <div class="field">
                  <label for="quiz-title">Quiz Title</label>
                  <input class="input" id="quiz-title" name="quiz-title" type="text" autocomplete="off"
                         placeholder="Loops & Conditionals Check…" required maxlength="80" />
                  <p class="field-error" id="quiz-title-error" hidden>Give the quiz a title before saving.</p>
                </div>
                <div class="field">
                  <label for="quiz-subject">Subject</label>
                  <select class="input input--select" id="quiz-subject" name="quiz-subject">
                  </select>
                </div>
                <div class="field">
                  <label for="quiz-desc">Description <span class="opt">(optional)</span></label>
                  <textarea class="input textarea" id="quiz-desc" name="quiz-desc" rows="3" maxlength="200"
                            placeholder="One line on what this quiz covers…"></textarea>
                </div>

{publish}

{schedule}

{timed}

{hints}

{shuffle}

                <div class="btnrow">
                  <button class="btn btn--primary" type="submit" id="btn-save-quiz">Save Quiz</button>
                </div>
              </form>

              <section class="panel" data-od-id="question-list" aria-labelledby="qlist-title">
                <div class="panel__head">
                  <h3 class="panel__title" id="qlist-title">Questions</h3>
                  <span class="pill" id="qlist-count">0</span>
                </div>
                <ol class="qlist" id="question-list"></ol>
                <div class="empty empty--tight" id="qlist-empty">
                  <p class="empty__note">No questions yet — add the first one →</p>
                </div>
              </section>
            </div>

            <div class="bstack">
              <form class="panel qeditor" id="question-form" data-od-id="question-editor" novalidate>
                <div class="panel__head">
                  <h3 class="panel__title" id="qeditor-title">Add a Question</h3>
                  <div class="qhead-tools">
                    <span class="pill" id="qeditor-count">Question 0</span>
                    <button class="iconbtn iconbtn--sm qsave-btn" type="button" id="btn-save-template"
                            title="Save as template" aria-label="Save this question as a template">
                      {icon("i-template")}
                    </button>
                    <button class="iconbtn iconbtn--sm qsave-btn" type="button" id="btn-save-fav"
                            title="Save as favourite" aria-label="Save this question as a favourite">
                      {icon("i-star")}
                    </button>
                  </div>
                </div>

                <div class="field">
                  <label for="q-text">Question</label>
                  <input class="input" id="q-text" name="q-text" type="text" autocomplete="off"
                         placeholder="Which loop checks its condition first?…" required maxlength="200" />
                  <p class="field-error" id="q-text-error" hidden>Enter the question text first.</p>
                </div>

                <fieldset class="choices">
                  <legend class="visually-hidden">Answer options — select the radio of the correct answer</legend>
                  <div class="choices__row" id="choices-row"></div>
                  <p class="field-error" id="q-choices-error" hidden>Fill every option and mark one correct answer.</p>
                </fieldset>

                <div class="btnrow btnrow--spread">
                  <div class="btnrow">
                    <button class="btn btn--primary" type="submit" id="btn-save-question">Add Question</button>
                    <button class="btn btn--ghost" type="button" id="btn-clear-question" hidden>Clear Form</button>
                  </div>
                  <button class="btn btn--outline" type="button" id="btn-play-current">
                    {icon("i-play")}Preview Quiz
                  </button>
                </div>
              </form>

              <section class="panel" data-od-id="roster" aria-labelledby="roster-title">
                <div class="panel__head">
                  <h3 class="panel__title" id="roster-title">Class Roster</h3>
                  <span class="pill" id="roster-count">0</span>
                </div>
                <ul class="roster" id="roster-list"></ul>
                <p class="field-note">Attendance % on the dashboard is computed against this roster.</p>
              </section>
            </div>

          </div>
        </section>'''


# ─── 10. results view ────────────────────────────────────────────────
def view_results() -> str:
    rstats = "\n\n".join([
        _rstat_card("1"),
        _rstat_card("2"),
        _rstat_card("3", accent=True),
    ])
    return f'''        <!-- ─────────── Results ─────────── -->
        <section class="view" id="view-results" data-od-id="view-results" aria-labelledby="results-heading" hidden>
          <h2 class="visually-hidden" id="results-heading">Results</h2>

          <div class="statstrip statstrip--3" data-od-id="result-stats">
{rstats}
          </div>

          <section class="panel" data-od-id="results-table" aria-labelledby="results-table-title">
            <div class="panel__head">
              <h2 class="panel__title" id="results-table-title">Score Ledger</h2>
              <div class="res-search">
                {icon("i-search")}
                <input id="results-search" type="search" autocomplete="off"
                       placeholder="Search quizzes by topic…"
                       aria-label="Search quizzes by topic" />
              </div>
            </div>

            <div id="results-groups" class="rg-list"></div>

            <!-- Filter + Export toolbar — parked here, moved into whichever quiz row is expanded -->
            <div class="btnrow res-filters-wrap" id="results-toolbar" hidden>
              <button class="btn btn--outline btn--sm" type="button" id="btn-results-filter"
                      aria-haspopup="true" aria-expanded="false" aria-controls="results-filters">
                {icon("i-funnel")}Filter
              </button>
              <button class="btn btn--outline btn--sm" type="button" id="btn-export-csv">
                {icon("i-download")}Export CSV
              </button>
              <div class="res-filters" id="results-filters" hidden>
                <div class="seg" role="group" aria-label="Attendance" id="results-filter-att">
                  <button class="seg__btn is-active" type="button" data-att="all">All</button>
                  <button class="seg__btn" type="button" data-att="present">Present</button>
                  <button class="seg__btn" type="button" data-att="absent">Absent</button>
                </div>
                <div class="seg" role="group" aria-label="Result" id="results-filter-res">
                  <button class="seg__btn" type="button" data-res="pass">Pass</button>
                  <button class="seg__btn" type="button" data-res="fail">Fail</button>
                </div>
                <div class="res-filter-grid">
                  <label>Marks ≥<input class="input" id="flt-marks-min" type="number" min="0" inputmode="numeric" placeholder="e.g. 5" /></label>
                  <label>Marks ≤<input class="input" id="flt-marks-max" type="number" min="0" inputmode="numeric" placeholder="e.g. 8" /></label>
                  <label>Time ≤ (min)<input class="input" id="flt-time-max" type="number" min="0" inputmode="numeric" placeholder="e.g. 10" /></label>
                  <label>Time ≥ (min)<input class="input" id="flt-time-min" type="number" min="0" inputmode="numeric" placeholder="e.g. 2" /></label>
                </div>
                <div class="res-filter-actions">
                  <button class="btn btn--ghost btn--sm" type="button" id="flt-clear">Clear all</button>
                  <button class="btn btn--primary btn--sm" type="button" id="flt-apply">Apply</button>
                </div>
              </div>
            </div>
            <div class="empty" id="results-empty">
              <p class="empty__title" id="results-empty-title">No attempts yet</p>
              <p class="empty__note" id="results-empty-note">Play a quiz to see scores land in the ledger.</p>
              <button class="btn btn--outline" type="button" data-nav="dashboard">Back to Dashboard</button>
            </div>
          </section>
        </section>'''


# ─── 11. drafts / favourites / templates views ───────────────────────
def view_drafts() -> str:
    return '''      <!-- ─────────── Drafts ─────────── -->
      <section class="view" id="view-drafts" data-od-id="view-drafts" aria-labelledby="drafts-heading" hidden>
        <h2 class="visually-hidden" id="drafts-heading">Drafts</h2>
        <section class="panel" data-od-id="drafts-panel" aria-labelledby="drafts-panel-title">
          <div class="panel__head">
            <h3 class="panel__title" id="drafts-panel-title">Drafted Quizzes</h3>
            <span class="pill" id="drafts-count">0</span>
          </div>
          <p class="panel-sub">Unpublished quizzes — press “Continue editing” to pick one back up in the builder.</p>
          <div class="drafts-rows" id="drafts-rows"></div>
          <div class="empty" id="drafts-empty">
            <p class="empty__title">No drafts</p>
            <p class="empty__note">Saved quizzes land here until you publish them.</p>
            <button class="btn btn--outline" type="button" data-nav="builder">Open Quiz Builder</button>
          </div>
        </section>
      </section>'''


def _lib_view(view_id: str, heading: str, title_id: str, title: str,
              search_label: str, count_id: str, search_id: str,
              filter_btn_id: str, filter_id: str, opts_id: str,
              sub: str, rows_id: str, empty_id: str,
              empty_title: str, empty_note: str,
              outer_labelledby: str = "") -> str:
    panel_id = f"{view_id.replace('view-', '')}-panel"
    outer_lb = outer_labelledby or title_id
    return f'''      <section class="view" id="{view_id}" data-od-id="{view_id}" aria-labelledby="{outer_lb}" hidden>
        <h2 class="visually-hidden" id="{heading}">{title}</h2>
        <section class="panel" data-od-id="{panel_id}" aria-labelledby="{title_id}">
          <div class="panel__head">

            <h3 class="panel__title" id="{title_id}">{title}</h3>
            <div class="lib-tools">
              <span class="pill" id="{count_id}">0</span>
              <label class="lib-search">
                {icon("i-search")}
                <input type="search" id="{search_id}" placeholder="Search by keyword…" aria-label="{search_label}" />
              </label>
              <div class="lib-filter-wrap">
                <button class="iconbtn iconbtn--sm" type="button" id="{filter_btn_id}" aria-haspopup="dialog"
                        aria-expanded="false" aria-controls="{filter_id}" title="Filter by subject">
                  {icon("i-funnel")}
                </button>
                <div class="lib-filter" id="{filter_id}" hidden>
                  <p class="drafts-flyout__head">Subject</p>
                  <div class="lib-filter__opts" id="{opts_id}"></div>
                </div>
              </div>
            </div>
          </div>
          <p class="panel-sub">{sub}</p>
          <div class="lib-rows" id="{rows_id}"></div>
          <div class="empty" id="{empty_id}">
            <p class="empty__title">{empty_title}</p>
            <p class="empty__note">{empty_note}</p>
          </div>
        </section>
      </section>'''


def view_favs() -> str:
    return _lib_view(
        "view-favs", "favs-heading", "favs-panel-title", "Favourite Questions",
        "Search favourite questions", "favs-count", "favs-search",
        "favs-filter-btn", "favs-filter", "favs-filter-opts",
        "Questions you starred in the editor — click a row to load it into the builder form.",
        "favs-rows", "favs-empty",
        "No favourites yet",
        "Tap the star beside “Question N” in the question editor to save one.",
        outer_labelledby="favs-heading",
    )


def view_bookmarks() -> str:
    return _lib_view(
        "view-bookmarks", "bookmarks-heading", "bookmarks-panel-title", "Reusable Templates",
        "Search saved templates", "bookmarks-count", "bookmarks-search",
        "bookmarks-filter-btn", "bookmarks-filter", "bookmarks-filter-opts",
        "Question templates — click a row to load it into the builder form.",
        "bookmarks-rows", "bookmarks-empty",
        "No templates yet",
        "Tap the template icon beside “Question N” in the question editor to save one.",
        outer_labelledby="bookmarks-heading",
    )


# ─── 12. AI generator view ───────────────────────────────────────────
def view_generate() -> str:
    return f'''      <!-- ─────────── AI Generator / AI Practice ─────────── -->
      <section class="view" id="view-generate" data-od-id="view-generate" aria-labelledby="generate-heading" hidden>
        <h2 class="visually-hidden" id="generate-heading">AI Quiz Generator</h2>

        <div class="gen-grid" data-od-id="gen-grid">

          <!-- Source panel -->
          <form class="panel gen-side" id="gen-form" data-od-id="gen-source" novalidate>
            <div class="panel__head">
              <h3 class="panel__title" id="gen-form-title">From Your Notes</h3>
              <span class="pill pill--accent">Gemini</span>
            </div>

            <div class="seg seg--block" role="group" aria-label="Source type">
              <button class="seg__btn is-active" type="button" data-source="pdf" aria-pressed="true">
                {icon("i-file")}PDF Notes
              </button>
              <button class="seg__btn" type="button" data-source="youtube" aria-pressed="false">
                {icon("i-yt")}YouTube Link
              </button>
            </div>
            <div class="dropzone" id="gen-dropzone" role="button" tabindex="0"
                 aria-label="Upload a PDF — click or press Enter to browse, or drop a file here"
                 aria-describedby="gen-file-note">
              <input type="file" id="gen-file-input" accept="application/pdf,.pdf" hidden />
              <span class="dropzone__icon ico" aria-hidden="true"><svg class="ico"><use href="#i-file"></use></svg></span>
              <p class="dropzone__title" id="gen-drop-title">Drop a PDF or click to browse</p>
              <p class="dropzone__note" id="gen-file-note">Lecture notes, slides exports, chapters — up to 15&nbsp;MB</p>
            </div>

            <div class="field" id="gen-url-field" hidden>
              <label for="gen-url">YouTube URL</label>
              <input class="input" id="gen-url" name="gen-url" type="url" inputmode="url" autocomplete="off" spellcheck="false"
                     placeholder="https://www.youtube.com/watch?v=…" />
              <p class="field-error" id="gen-url-error" hidden>That doesn't look like a YouTube link — paste a youtube.com or youtu.be URL.</p>
            </div>

            <div class="field" id="gen-subject-field">
              <label for="gen-subject">Subject</label>
              <select class="input input--select" id="gen-subject" name="gen-subject">
              </select>
              <p class="field-note">Generated questions are filed under this subject.</p>
            </div>

            <div class="field">
              <label for="gen-count">Questions to Generate</label>
              <select class="input input--select" id="gen-count" name="gen-count">
                <option value="5">5 questions</option>
                <option value="8" selected>8 questions</option>
                <option value="10">10 questions</option>
                <option value="12">12 questions</option>
              </select>
            </div>

            <div class="btnrow">
              <button class="btn btn--primary" type="submit" id="btn-generate">
                {icon("i-spark")}Generate Quiz
              </button>
            </div>
            <p class="field-error" id="gen-error" role="alert"></p>
          </form>

          <!-- Result panel -->
          <section class="panel gen-result" id="gen-result-panel" data-od-id="gen-result" aria-labelledby="gen-result-title">
            <div class="panel__head">
              <h3 class="panel__title" id="gen-result-title">Draft Quiz</h3>
              <span class="pill" id="gen-status-pill" hidden></span>
            </div>

            <div class="empty" id="gen-idle">
              <p class="empty__title">Generated questions land here</p>
              <p class="empty__note">Drop a PDF or paste a YouTube link, pick the subject, and the drafted quiz appears on the right for review before anything is saved.</p>
            </div>

            <div class="gen-loading" id="gen-loading" hidden>
              <span class="spinner" aria-hidden="true"></span>
              <p class="gen-loading__title" id="gen-loading-title">Reading your notes…</p>
              <p class="gen-loading__note" id="gen-loading-note">This usually takes 10–30 seconds.</p>
            </div>

            <div class="gen-error" id="gen-fail" hidden>
              <p class="gen-fail__title">Generation didn't finish</p>
              <p class="gen-fail__note" id="gen-fail-note">Something went wrong.</p>
              <button class="btn btn--outline" type="button" id="btn-gen-retry">Try Again</button>
            </div>

            <div class="gen-review" id="gen-review" hidden>
              <div class="gen-review__head">
                <div>
                  <p class="gen-review__qtitle" id="gen-review-title">—</p>
                  <p class="gen-review__meta" id="gen-review-meta">—</p>
                </div>
                <div class="btnrow">
                  <button class="btn btn--outline" type="button" id="btn-gen-discard">Discard</button>
                  <button class="btn btn--primary" type="button" id="btn-gen-save"><span id="gen-save-label">Save to Workspace</span></button>
                </div>
              </div>
              <ol class="genlist" id="gen-list"></ol>
            </div>
          </section>
        </div>
      </section>
      </main>
    </div>
  </div>'''

# ─── 13. modals ──────────────────────────────────────────────────────
def modal_player() -> str:
    return f'''  <!-- ══════════════════ Player modal ══════════════════ -->
  <div class="modal" id="player-modal" role="dialog" aria-modal="true"
       aria-labelledby="player-title" hidden>
    <div class="modal__backdrop" data-close-player></div>
    <div class="modal__card player" role="document" data-od-id="player">
      <header class="player__head">
        <div>
          <p class="eyebrow" id="player-eyebrow">Now Playing</p>
          <h2 class="player__title" id="player-title">Quiz</h2>
        </div>
        <div class="player__head-actions">
          <button class="iconbtn" type="button" id="btn-player-fav" aria-label="Save this question as favourite" aria-pressed="false" hidden>
            {icon("i-star")}
          </button>
          <button class="iconbtn" type="button" id="btn-close-player" aria-label="Close quiz player">
            {icon("i-x")}
          </button>
        </div>
      </header>

      <div class="player__body" id="player-body"><!-- steps rendered by the app script --></div>

      <footer class="player__foot">
        <div class="progress" role="progressbar" aria-label="Quiz progress"
             aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" id="player-progress">
          <span class="progress__bar" id="player-progress-bar"></span>
        </div>
        <div class="player__foot-row">
          <p class="meta" id="player-step-label">Ready</p>
          <div class="btnrow" id="player-actions"><!-- buttons rendered by the app script --></div>
        </div>
      </footer>
    </div>
  </div>'''


def modal_plans() -> str:
    return f'''  <!-- ══════════════════ Plans modal ══════════════════ -->
  <div class="modal" id="plans-modal" role="dialog" aria-modal="true"
       aria-labelledby="plans-title" hidden>
    <div class="modal__backdrop" data-close-plans></div>
    <div class="modal__card modal__card--plans" role="document">
      <div class="plans__head">
        <div>
          <p class="eyebrow">Membership</p>
          <h2 class="confirm-title" id="plans-title" style="margin:0">Choose your plan</h2>
        </div>
        <button class="iconbtn" type="button" id="btn-close-plans" aria-label="Close plans">
          {icon("i-x")}
        </button>
      </div>
      <div class="plans-grid" id="plans-grid"></div>
    </div>
  </div>'''


def modal_confirm() -> str:
    return '''  <!-- ══════════════════ Confirm dialog ══════════════════ -->
  <div class="modal" id="confirm-modal" role="dialog" aria-modal="true"
       aria-labelledby="confirm-title" aria-describedby="confirm-msg" hidden>
    <div class="modal__backdrop" data-close-confirm></div>
    <div class="modal__card modal__card--sm" role="document">
      <h2 class="confirm-title" id="confirm-title">Are you sure?</h2>
      <p class="confirm-msg" id="confirm-msg" role="status">This action can't be undone.</p>
      <div class="btnrow btnrow--end">
        <button class="btn btn--outline" type="button" id="btn-confirm-cancel">Cancel</button>
        <button class="btn btn--danger" type="button" id="btn-confirm-ok">Confirm</button>
      </div>
    </div>
  </div>'''


def modal_import() -> str:
    return f'''  <!-- ══════════════════ Import dialog ══════════════════ -->
  <div class="modal" id="import-modal" role="dialog" aria-modal="true"
       aria-labelledby="import-title" hidden>
    <div class="modal__backdrop" data-close-import></div>
    <div class="modal__card modal__card--sm" role="document">
      <h2 class="confirm-title" id="import-title">Import JSON</h2>
      <p class="confirm-msg">Upload a previously exported workspace file, or paste its JSON below. Importing replaces the current data.</p>
      <div class="field import-upload-row">
        <input type="file" id="import-file" accept=".json,application/json" hidden>
        <button class="btn btn--outline" type="button" id="btn-import-file">
          {icon("i-upload")}Upload file…
        </button>
        <span class="meta" id="import-file-name"></span>
      </div>
      <div class="field">
        <label for="import-text" class="visually-hidden">JSON workspace</label>
        <textarea class="input textarea textarea--mono" id="import-text" rows="6"
                  spellcheck="false" placeholder='{{"quizzes":[…]}}'></textarea>
        <p class="field-error" id="import-error" hidden>That doesn't parse as JSON — check the file and paste again.</p>
      </div>
      <div class="btnrow btnrow--end">
        <button class="btn btn--outline" type="button" id="btn-import-cancel">Cancel</button>
        <button class="btn btn--primary" type="button" id="btn-import-ok">Import Workspace</button>
      </div>
    </div>
  </div>'''


_ACCENTS = [("coral", "Coral"), ("mustard", "Mustard"), ("olive", "Olive")]


def modal_subject() -> str:
    accent_btns = []
    for i, (key, label) in enumerate(_ACCENTS):
        active = " is-active" if i == 0 else ""
        pressed = "true" if i == 0 else "false"
        accent_btns.append(
            f'''          <button class="subject-accent{active}" type="button" data-accent="{key}" aria-pressed="{pressed}"
                  title="{label}"><span class="sub-dot" data-accent="{key}"></span>{label}</button>'''
        )
    accents = "\n".join(accent_btns)
    return f'''  <div class="modal" id="subject-modal" role="dialog" aria-modal="true"
       aria-labelledby="subject-title" hidden>
    <div class="modal__backdrop" data-close-subject></div>
    <div class="modal__card modal__card--sm" role="document">
      <h2 class="confirm-title" id="subject-title">New Subject</h2>
      <p class="confirm-msg">New subjects appear everywhere subjects can be picked — leaderboard, quiz builder, generator and results.</p>
      <div class="field">
        <label for="subject-name">Name</label>
        <input class="input" id="subject-name" type="text" autocomplete="off" maxlength="60"
               placeholder="e.g. Operating Systems" />
      </div>
      <div class="field">
        <label for="subject-short">Short code <span class="opt">(used in compact tables)</span></label>
        <input class="input" id="subject-short" type="text" autocomplete="off" maxlength="6"
               placeholder="e.g. OS" />
      </div>
      <div class="field">
        <label for="subject-desc">Description <span class="opt">(optional)</span></label>
        <input class="input" id="subject-desc" type="text" autocomplete="off" maxlength="120"
               placeholder="One line on what this subject covers…" />
      </div>
      <div class="field">
        <label>Accent</label>
        <div class="subject-accent-row" id="subject-accent-row" role="radiogroup" aria-label="Accent color">
{accents}
        </div>
      </div>
      <p class="field-error" id="subject-error" hidden></p>
      <div class="btnrow btnrow--end">
        <button class="btn btn--outline" type="button" id="btn-subject-cancel">Cancel</button>
        <button class="btn btn--primary" type="button" id="btn-subject-ok">Add Subject</button>
      </div>
    </div>
  </div>'''


def modal_student() -> str:
    return '''  <!-- ══════════════════ New Student dialog ══════════════════ -->
  <div class="modal" id="student-modal" role="dialog" aria-modal="true"
       aria-labelledby="student-title" hidden>
    <div class="modal__backdrop" data-close-student></div>
    <div class="modal__card modal__card--sm" role="document">
      <h2 class="confirm-title" id="student-title">New Student</h2>
      <p class="confirm-msg">You issue the login credentials. The student can sign in only after the account is published — untick to prepare it now and activate later.</p>
      <div class="field">
        <label for="student-name">Full name</label>
        <input class="input" id="student-name" type="text" autocomplete="off" maxlength="60"
               placeholder="e.g. Aarav Sharma" />
      </div>
      <div class="field">
        <label for="student-email">Email <span class="opt">(used to sign in)</span></label>
        <input class="input" id="student-email" type="email" autocomplete="off" maxlength="80"
               placeholder="e.g. aarav@school.edu" />
      </div>
      <div class="field">
        <label for="student-pass">Password <span class="opt">(min 6 chars — share it with the student)</span></label>
        <input class="input" id="student-pass" type="text" autocomplete="off" maxlength="80"
               placeholder="Set a starting password" />
      </div>
      <label class="snap-check" for="student-publish" style="margin-bottom:var(--sp-4)">
        <input type="checkbox" id="student-publish" checked />
        <span>Publish immediately — student can sign in right away</span>
      </label>
      <p class="field-error" id="student-error" hidden></p>
      <div class="btnrow btnrow--end">
        <button class="btn btn--outline" type="button" id="btn-student-cancel">Cancel</button>
        <button class="btn btn--primary" type="button" id="btn-student-ok">Create Student</button>
      </div>
    </div>
  </div>
'''


def modal_notice() -> str:
    return '''  <!-- ══════════════════ Notice dialog ══════════════════ -->
  <div class="modal" id="notice-modal" role="dialog" aria-modal="true"
       aria-labelledby="notice-title" hidden>
    <div class="modal__backdrop" data-close-notice></div>
    <div class="modal__card modal__card--sm" role="document">
      <h2 class="confirm-title" id="notice-title">Add Pinned Notice</h2>
      <p class="confirm-msg" id="notice-sub">The notice appears pinned to the subject row in the Quiz Ledger.</p>
      <div class="field">
        <label for="notice-name">Name</label>
        <input class="input" id="notice-name" type="text" autocomplete="off" maxlength="60"
               placeholder="e.g. Unit test next Monday" />
      </div>
      <div class="field">
        <label for="notice-desc">Description <span class="opt">(optional)</span></label>
        <input class="input" id="notice-desc" type="text" autocomplete="off" maxlength="160"
               placeholder="Extra detail students should see…" />
      </div>
      <div class="btnrow btnrow--end">
        <button class="btn btn--outline" type="button" id="btn-notice-cancel">Cancel</button>
        <button class="btn btn--primary" type="button" id="btn-notice-ok">Pin Notice</button>
      </div>
    </div>
  </div>'''


# ─── 14. toast + icon sprite + footer ────────────────────────────────
_SPRITE_SYMBOLS = [
    ("i-gauge", '<path d="M12 4a9 9 0 0 1 9 9c0 2.4-1 4.6-2.5 6.2M12 4a9 9 0 0 0-9 9c0 2.4 1 4.6 2.5 6.2M12 4v2.5M4.2 17.5h15.6M12 13.5 15.8 9"/>'),
    ("i-pen", '<path d="m4 20 .9-3.6L16.2 5.1a2 2 0 0 1 2.8 0l-.1-.1a2 2 0 0 1 0 2.8L7.6 19.1 4 20Z"/>'),
    ("i-ledger", '<path d="M5 4h11l3 3v13H5V4Z"/><path d="M9 9h6M9 12.5h6M9 16h4"/>'),
    ("i-play", '<path d="M8 5.5v13l11-6.5L8 5.5Z"/>'),
    ("i-plus", '<path d="M12 5v14M5 12h14"/>'),
    ("i-x", '<path d="m6 6 12 12M18 6 6 18"/>'),
    ("i-download", '<path d="M12 4v11m0 0 4.5-4.5M12 15l-4.5-4.5M5 19.5h14"/>'),
    ("i-upload", '<path d="M12 20V9m0 0 4.5 4.5M12 9 7.5 13.5M5 4.5h14"/>'),
    ("i-trash", '<path d="M5 7h14M9.5 7V5h5v2M7 7l1 13h8l1-13M10.2 10.5v6M13.8 10.5v6"/>'),
    ("i-edit", '<path d="m4 20 .9-3.6L16.2 5.1a2 2 0 0 1 2.8 2.8L7.6 19.1 4 20ZM14 7l3 3"/>'),
    ("i-copy", '<rect x="9" y="9" width="11" height="11" rx="1.5"/><path d="M5 15H4V4h11v1"/>'),
    ("i-spark", '<path d="M12 3.5 13.9 9 19.5 11 13.9 13 12 18.5 10.1 13 4.5 11 10.1 9 12 3.5Z"/><path d="M18.5 16.5 19.2 18.5 21.2 19.2 19.2 19.9 18.5 21.9 17.8 19.9 15.8 19.2 17.8 18.5 18.5 16.5Z"/>'),
    ("i-file", '<path d="M6 3.5h8L19 8.5v12H6V3.5Z"/><path d="M13.5 4v5h5"/>'),
    ("i-yt", '<rect x="3" y="6" width="18" height="12.5" rx="3.5"/><path d="M10.2 9.5v5.5L15 12.2 10.2 9.5Z"/>'),
    ("i-sun", '<circle cx="12" cy="12" r="4"/><path d="M12 2.5v2.4M12 19.1v2.4M2.5 12h2.4M19.1 12h2.4M5.3 5.3l1.7 1.7M17 17l1.7 1.7M18.7 5.3 17 7M7 17l-1.7 1.7"/>'),
    ("i-moon", '<path d="M20 14.5A8.5 8.5 0 0 1 9.5 4a8.5 8.5 0 1 0 10.5 10.5Z"/>'),
    ("i-cap", '<path d="M12 4 2.5 8.5 12 13l9.5-4.5L12 4Z"/><path d="M6 10.7V15c0 1.6 2.7 3 6 3s6-1.4 6-3v-4.3"/><path d="M21.5 8.5V14"/>'),
    ("i-book", '<path d="M5 4h13a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H7a2 2 0 0 1-2-2V4Z"/><path d="M5 17.5A2.5 2.5 0 0 1 7.5 15H19"/>'),
    ("i-swap", '<path d="M7 8h11m0 0-3.5-3.5M18 8l-3.5 3.5M17 16H6m0 0 3.5-3.5M6 16l3.5 3.5"/>'),
    ("i-chevron", '<path d="m6 9 6 6 6-6"/>'),
    ("i-clock", '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'),
    ("i-dollar", '<path d="M12 3v18M16.2 6.8c-.7-1.2-2.3-1.9-4.2-1.9-2.4 0-4.3 1.3-4.3 3.3 0 4.4 8.9 2.3 8.9 6.9 0 2-2 3.4-4.6 3.4-2.1 0-3.9-.8-4.6-2.1"/>'),
    ("i-logout", '<path d="M14 4h4.5v16H14M4 12h10m0 0-3.5-3.5M14 12l-3.5 3.5"/>'),
    ("i-bars", '<rect x="4" y="4" width="4" height="16" rx="1"/><rect x="10" y="7" width="4" height="13" rx="1"/><rect x="16" y="5" width="4" height="15" rx="1"/>'),
    ("i-funnel", '<path d="M4 5h16l-6.2 7.3V19l-3.6-2v-4.7L4 5Z"/>'),
    ("i-search", '<circle cx="11" cy="11" r="7"/><path d="m20.5 20.5-4.6-4.6"/>'),
    ("i-bookmark", '<path d="M6.5 4h11v16l-5.5-4-5.5 4V4Z"/>'),
    ("i-bell", '<path d="M6 10a6 6 0 0 1 12 0c0 4 1.5 5.5 2.5 6.5H3.5C4.5 15.5 6 14 6 10Z"/><path d="M10 19.5a2 2 0 0 0 4 0"/>'),
    ("i-pin", '<path d="M9 4h6l-1 7 3.5 3v2h-11v-2L10 11 9 4Z"/><path d="M12 16v4.5"/>'),
    ("i-template", '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M4 9.5h16M9.5 9.5V20"/>'),
    ("i-star", '<path d="m12 3.5 2.6 5.3 5.9.9-4.3 4.1 1 5.9-5.2-2.8-5.2 2.8 1-5.9-4.3-4.1 5.9-.9L12 3.5Z"/>'),
]


def toast() -> str:
    return '  <div class="toast" id="toast" role="status" aria-live="polite" hidden></div>'


def icon_sprite() -> str:
    symbols = "\n".join(
        f'    <symbol id="{sid}" viewBox="0 0 24 24">{path}</symbol>'
        for sid, path in _SPRITE_SYMBOLS
    )
    return f'''  <!-- Icon sprite -->
  <svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">
{symbols}
  </svg>'''


def script_tag() -> str:
    return '  <script src="app.js"></script>'


# ─── build ───────────────────────────────────────────────────────────
def build() -> str:
    """Compose every section into the final page."""
    parts = [
        head_section(),
        skip_link(),
        login_gate(),
        consent_banner(),
        brand_rail(),
        phone_tabbar(),
        topbar(),
        view_leaderboard(),
        view_dashboard(),
        view_builder(),
        view_results(),
        view_drafts(),
        view_favs(),
        view_bookmarks(),
        view_generate(),
        modal_player(),
        modal_plans(),
        modal_confirm(),
        modal_import(),
        modal_subject(),
        modal_student(),
        modal_notice(),
        toast(),
        icon_sprite(),
        script_tag(),
    ]
    return "\n".join(parts) + "\n</body>\n</html>\n"


def main() -> None:
    html = build()
    OUT.write_text(html, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(html.splitlines())} lines, {len(html)} bytes)")


if __name__ == "__main__":
    main()
